// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCntBrq5pSyhWV87JDiZqnOCuouUUFoVyo',
    appId: '1:1064319967640:web:a648cdf173ffa237984bed',
    messagingSenderId: '1064319967640',
    projectId: 'take-care-mom-firebase',
    authDomain: 'take-care-mom-firebase.firebaseapp.com',
    storageBucket: 'take-care-mom-firebase.appspot.com',
    measurementId: 'G-TKN2TP59KR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeKNOmASnvKNHDsrg5WfkE7hEwz6p_Z8Q',
    appId: '1:1064319967640:android:663899aaff226eb6984bed',
    messagingSenderId: '1064319967640',
    projectId: 'take-care-mom-firebase',
    storageBucket: 'take-care-mom-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5AuZHcVU8OuJ8UL4aTBGL2pzHtP6QGCc',
    appId: '1:1064319967640:ios:177e5d5faaadd417984bed',
    messagingSenderId: '1064319967640',
    projectId: 'take-care-mom-firebase',
    storageBucket: 'take-care-mom-firebase.appspot.com',
    iosBundleId: 'com.example.auth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5AuZHcVU8OuJ8UL4aTBGL2pzHtP6QGCc',
    appId: '1:1064319967640:ios:3301128bfb0cae09984bed',
    messagingSenderId: '1064319967640',
    projectId: 'take-care-mom-firebase',
    storageBucket: 'take-care-mom-firebase.appspot.com',
    iosBundleId: 'com.example.auth.RunnerTests',
  );
}
